name: iOS Localization

on:
  push:
    branches:
      - main # Or your main development branch
  pull_request:
    branches:
      - main

jobs:
  localize:
    runs-on: macos-14
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_16.1.app/Contents/Developer

      - name: Build Xcode Project
        run: |
          xcodebuild -project LocalizerExample.xcodeproj -scheme LocalizerExample -configuration Debug -sdk iphonesimulator CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO build
          # Copy the updated xcstrings file from build output to source
          find ~/Library/Developer/Xcode/DerivedData -name "Localizable.xcstrings" -newer LocalizerExample/Resources/Localizable.xcstrings -exec cp {} LocalizerExample/Resources/Localizable.xcstrings \; 2>/dev/null || true

      - name: Run iOS Localizer
        uses: eilonkr/ios-localizer-action@v0.5.5
        with:
          xcstrings_file_path: 'LocalizerExample/Resources/Localizable.xcstrings' 
          target_languages: 'de,es,fr'
          github_token: ${{ secrets.GITHUB_TOKEN }}

          # Optional customizations:
          # pr_branch_prefix: 'localization-updates/'
          # commit_message: 'i18n: Update translations in Localizable.xcstrings'
          # pr_title: 'New Translations Added'
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}