name: iOS Localization

on:
  push:
    branches:
      - main # Or your main development branch
  pull_request:
    branches:
      - main

jobs:
  localize:
    runs-on: macos-14
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_16.1.app/Contents/Developer

      - name: Build Xcode Project
        run: |
          xcodebuild -project LocalizerExample.xcodeproj -scheme LocalizerExample -configuration Debug -sdk iphonesimulator CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO build

      - name: Copy Updated Localizable.xcstrings
        run: |
          echo "=== Before copy ==="
          ls -la LocalizerExample/Resources/Localizable.xcstrings
          cat LocalizerExample/Resources/Localizable.xcstrings
          echo "=== Searching for all Localizable.xcstrings files on runner ==="
          find /Users/runner -name "Localizable.xcstrings" 2>/dev/null || echo "No files found with find command"
          echo "=== Specifically checking DerivedData ==="
          ls -la /Users/runner/Library/Developer/Xcode/DerivedData/ 2>/dev/null || echo "DerivedData directory not found"
          find /Users/runner/Library/Developer/Xcode/DerivedData -name "Localizable.xcstrings" -exec echo "Found at: {}" \; -exec ls -la {} \; -exec cat {} \; 2>/dev/null || echo "No xcstrings files found in DerivedData"
          echo "=== Checking build output directory ==="
          find . -path "*/Build/Products/*" -name "Localizable.xcstrings" -exec echo "Found at: {}" \; -exec ls -la {} \; -exec cat {} \; 2>/dev/null || echo "No xcstrings files found in Build/Products"
          # Try to copy from any found location
          find /Users/runner -name "Localizable.xcstrings" -not -path "*/LocalizerExample/Resources/*" -exec cp {} LocalizerExample/Resources/Localizable.xcstrings \; 2>/dev/null || echo "No build-generated file found to copy"
          # Copy to a known location for artifact upload
          find /Users/runner -name "Localizable.xcstrings" -not -path "*/LocalizerExample/Resources/*" -exec cp {} ./build-output-Localizable.xcstrings \; 2>/dev/null || echo "No build file for artifact"
          echo "=== After copy ==="
          ls -la LocalizerExample/Resources/Localizable.xcstrings
          cat LocalizerExample/Resources/Localizable.xcstrings

      - name: Upload Build Output Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-localizable-xcstrings
          path: build-output-Localizable.xcstrings
          if-no-files-found: warn

      - name: Run iOS Localizer
        uses: eilonkr/ios-localizer-action@v0.5.5
        with:
          xcstrings_file_path: 'LocalizerExample/Resources/Localizable.xcstrings' 
          target_languages: 'de,es,fr'
          github_token: ${{ secrets.GITHUB_TOKEN }}

          # Optional customizations:
          # pr_branch_prefix: 'localization-updates/'
          # commit_message: 'i18n: Update translations in Localizable.xcstrings'
          # pr_title: 'New Translations Added'
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}