name: iOS Localization

on:
  push:
    branches:
      - main # Or your main development branch
  pull_request:
    branches:
      - main

jobs:
  localize:
    runs-on: macos-14
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_16.1.app/Contents/Developer

      - name: Build Xcode Project
        run: |
          echo "DERIVED_DATA=DerivedData" >> $GITHUB_ENV
          xcodebuild -project LocalizerExample.xcodeproj -scheme LocalizerExample -configuration Debug -sdk iphonesimulator -derivedDataPath "DerivedData" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO build

      - name: Copy Updated Localizable.xcstrings
        run: |
          echo "=== Finding built .app bundle ==="
          APP_PATH=$(find "DerivedData/Build/Products/Debug-iphonesimulator" -name "*.app" | head -n 1)
          echo "Found app at: $APP_PATH"
          echo "=== Looking for Localizable.xcstrings in app bundle ==="
          find "$APP_PATH" -name "Localizable.xcstrings" -exec echo "Found at: {}" \; -exec ls -la {} \;
          echo "=== Copying from app bundle ==="
          cp "$APP_PATH/Localizable.xcstrings" LocalizerExample/Resources/Localizable.xcstrings
          cp "$APP_PATH/Localizable.xcstrings" ./build-output-Localizable.xcstrings

      - name: Upload Build Output Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-localizable-xcstrings
          path: build-output-Localizable.xcstrings
          if-no-files-found: warn

      - name: Run iOS Localizer
        uses: eilonkr/ios-localizer-action@v0.5.5
        with:
          xcstrings_file_path: 'LocalizerExample/Resources/Localizable.xcstrings' 
          target_languages: 'de,es,fr'
          github_token: ${{ secrets.GITHUB_TOKEN }}

          # Optional customizations:
          # pr_branch_prefix: 'localization-updates/'
          # commit_message: 'i18n: Update translations in Localizable.xcstrings'
          # pr_title: 'New Translations Added'
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}